/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VAKSToken } from "./VAKSToken";
export * as factories from "./factories";
export { VAKSToken__factory } from "./factories/VAKSToken__factory";
