FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY entrypoint.dev.sh /usr/local/bin/entrypoint.dev.sh
RUN chmod +x /usr/local/bin/entrypoint.dev.sh

ENTRYPOINT ["entrypoint.dev.sh"]
CMD ["npm", "run", "start:dev"]
